FROM alpine:3.20
# The binary is provided by GoReleaser (dockers_v2) under a platform subdir.
ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/onr /usr/local/bin/onr
COPY ${TARGETPLATFORM}/onr-admin /usr/local/bin/onr-admin
WORKDIR /root
EXPOSE 3300
ENTRYPOINT ["/usr/local/bin/onr"]
CMD ["--config", "/etc/onr/onr.yaml"]
